# Detekt Static Analysis Configuration File
build:
  maxIssues: 0
  excludeCorrectable: false

# Code Style Rules
style:
  active: true
  # Rule to enforce a maximum limit on method length
  LongMethod:
    active: true
    threshold: 30 # Function length limit set to 30 lines
    ignoreAnnotated: []

# Code Complexity Rules
complexity:
  active: true
  TooManyFunctions:
    active: true
    thresholdInFiles: 11
    thresholdInClasses: 11